# Библиотека Numpy

In [1]:
L=range(10000)
%timeit [i**2 for i in L]

4.21 ms ± 74.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [2]:
import numpy as np
L=np.arange(10000)
%timeit L**2

22.1 µs ± 93.2 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Основной объект - однородный массив ndarray
Его главные состовляющие:
* data - указатель в памяти на начало массива
* shape - размерности массива
* dtype - тип элементов массива
* stride - описание того, как считывать массив 

In [3]:
my_2d_array = np.arange(10).reshape((2, 5))

# Print out memory address
print(my_2d_array.data)

# Print out the shape of `my_array`
print(my_2d_array.shape)

# Print out the data type of `my_array`
print(my_2d_array.dtype)

# Print out the stride of `my_array`
print(my_2d_array.strides)

(2, 5)
int64
(40, 8)


### Способы задания массивов

In [4]:
# Create an array of ones
np.ones((3, 4))

# Create an array of zeros
np.zeros((2, 3, 4), dtype=np.int16)

# Create an array with random values
np.random.random((2, 2))

# Create an empty array
np.empty((3, 2))

# Create a full array
np.full((2, 2), 7)

# Create an array of evenly-spaced values
np.arange(10, 25, 5)

# Create an array of evenly-spaced values
np.linspace(0, 2, 9)

# Create a diagonal matrix
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### Exercise 

Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?


In [7]:
a = np.arange(1,6)
K = 3
np.concatenate([a.reshape((-1,1)), np.zeros((a.shape[0], K))], axis=1).reshape(-1)

array([ 1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  4.,
        0.,  0.,  0.,  5.,  0.,  0.,  0.])

### Индексация элементов массива

In [8]:
a = np.arange(10)
print(a[0], a[[3, -1]], a[3:], a[6: -2], a[:-3])

0 [3 9] [3 4 5 6 7 8 9] [6 7] [0 1 2 3 4 5 6]


In [9]:
a = np.diag(np.arange(3))
print(a[1, 2], a[1])

0 [0 1 0]


In [10]:
a = np.arange(10, 20)
mask = a % 3 == 0 
print(mask) 
print(a[mask])

a[mask] = -1
print(a)

[False False  True False False  True False False  True False]
[12 15 18]
[10 11 -1 13 14 -1 16 17 -1 19]


#### Exercise

Create a 8x8 matrix and fill it with a checkerboard pattern.

In [76]:
a = np.arange(1,9)
np.tile(np.concatenate([a, 9-a]), 4).reshape((8, 8)) % 2

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### Арифметические операции выполняются поэлементно

In [77]:
a = np.arange(1, 4)
print(a + 1)
print(2**a)
print(a**2)

[2 3 4]
[2 4 8]
[1 4 9]


### Функции над массивами

In [78]:
a = np.array([1, 2, 3])
print(np.sum(a), np.sin(a), np.mean(a), np.std(a))

a=np.arange(10).reshape((2, 5))
print(np.mean(a), np.mean(a, axis=0))

a = np.zeros((100, 100)) 
print(np.any(a != 0) , np.all(a == 0))

a = np.random.randn(5)
print(np.min(a), np.sort(a), np.argsort(a))

6 [ 0.84147098  0.90929743  0.14112001] 2.0 0.816496580928
4.5 [ 2.5  3.5  4.5  5.5  6.5]
False True
-1.04840513572 [-1.04840514 -0.41249802  0.05064238  0.24447632  0.91141517] [1 0 3 4 2]


#### Exercise

Generate a random 5x5 matrix. Subtract the mean of each row of a matrix.

In [83]:
a = np.random.rand(5,5)
a -= a.mean(axis=0)
a

array([[-0.35170864, -0.2139546 , -0.06701392,  0.07781741, -0.1647403 ],
       [ 0.05064473,  0.07873336,  0.37535402, -0.24653054,  0.35500754],
       [ 0.35192111,  0.05771946, -0.34900844, -0.32672148, -0.30723219],
       [-0.32951508,  0.32146341, -0.07711317, -0.06941247, -0.04999163],
       [ 0.27865787, -0.24396162,  0.11778151,  0.56484707,  0.16695659]])

### Сложение массивов

In [84]:
a = np.floor(10 * np.random.rand(2, 2))
print(a)

b = np.floor(10 * np.random.rand(2, 2))
print(b)

print('\n--Concatenate a and b--\n')

print(np.vstack((a, b))) # сложение по вертикали
print(np.hstack((a, b))) # сложение по горизонтали

[[ 2.  7.]
 [ 2.  0.]]
[[ 6.  7.]
 [ 0.  0.]]

--Concatenate a and b--

[[ 2.  7.]
 [ 2.  0.]
 [ 6.  7.]
 [ 0.  0.]]
[[ 2.  7.  6.  7.]
 [ 2.  0.  0.  0.]]


### Array broadcasting
Схема ниже показывает, как происходит скложение массивов. Если shape у массивов не совпадают, то массив меньшей размерности "естественным образом" дополняется до большей размерности.

![title](http://www.scipy-lectures.org/_images/numpy_broadcasting.png)

In [22]:
x = np.ones((3, 4))
y = np.random.rand(4)

# Add `x` and `y`. Note that `x` and `y` have different shapes.
print(x.shape, y.shape)
print(x + y)

(3, 4) (4,)
[[ 1.02100542  1.32549695  1.24321088  1.97304388]
 [ 1.02100542  1.32549695  1.24321088  1.97304388]
 [ 1.02100542  1.32549695  1.24321088  1.97304388]]


#### Exercise

Создайте масив first_column из четырех элементов: 0, 10, 20, 30. Затем создайте двухмерный массив 4x5, в котором первый столбец - массив first_column, а каждый элемент каждой строки, начиная со второго,  больше предыдущего элемента этой же строки на 1.

In [93]:
first_column = 10 * np.arange(0,4)
np.tile(first_column.reshape((-1,1)), 5) + np.arange(0,5)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

### Homework

1. Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.

1. Создайте двумерный массив 6x6, заполненный случайными значениями. Затем сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом.

2. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

3. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

4. По заданному двумерному массиву размера NxN постройте словарь, ключи которого - индексы диагоналей, параллельных побочной (нумерация начинается с 0), а значения - списки элементов исходного массива, лежащих на соответствующих диагоналях.
Решите задачу на примере массива a = np.arange(16).reshape(4, 4), в результате должен получиться словарь
{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}.

In [242]:
# 1
a = np.random.randn(10,3) / 100 + 0.5
print(a.mean())
# 2
b = np.random.rand(6,6)
print(b.sum(axis=1) / b.min(axis=0))
# 3
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
mask = np.roll(x==0, 1)
mask[0] = False
print(np.max(x[mask]))
# 4
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x[np.min(i):np.max(i)+1] += np.bincount(i)
print(x)
# 5
N = 4
a = np.arange(N * N).reshape((N, N))
print(a)
def mask(i):
    return (np.tri(N, N, i) + np.tri(N, N, -i).T) - 1
d = {2 * N - 1 - i : list(a[:,::-1][mask(i-3)==1]) for i in range(2 * N - 1)}
print(d)

0.50075035983
[  38.47123875    7.31227318    6.73038353    9.20424436   38.15761179
  115.16002804]
5
[ 2.  2.  2.  2.  1.  4.  1.  1.  2.  1.]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
{7: [15], 6: [11, 14], 5: [7, 10, 13], 4: [3, 6, 9, 12], 3: [2, 5, 8], 2: [1, 4], 1: [0]}
